### ISSUE TITLE
LESS import is slow

### ISSUE THREAD

**Issue by getvega** [zavoloklom/material-design-iconic-font#102]
Hi - and first thank you for this great repo. Glad someone has ported those icons to less!

We use it internally to have icons accessible directly within our LESS instead of loading the CSS as a separate file. Imho, this makes our HTML templates not too much polluted (see below).

The problem is that the zmdi import 

``` less
@import "bootstrap";
@import "material-design-iconic-font";
```

makes our gulp task compile the CSS in ~4s instead of 300ms (yes the whole bootstrap is compiled in less than 300ms...).

Any insight on how we can improve the zmdi import?
## Example

``` less
.menu i { .zmdi; }
.menu-settings i { .zmdi-settings; }
.menu-logout i { .zmdi-power; }
.menu-home i { .zmdi-home; }
```

**Comment by getvega** [comment]
Ok I figured that it was the `icon.less` icon declarations that were slow.

I managed to reduce the time to ~600ms by selecting icons I actually used within the project. A bit cumbersome... but I don't know why those declarations use that much time in LESS.

``` less
// custom-icons.less

@import "for";

@icons: airplane '\f103',
    money '\f19a',
    power '\f1af',
    print '\f1b0',
    refresh '\f1b9',
    settings '\f1c6',
    file '\f223',
    rotate-left '\f306',
    confirmation-number '\f3d4';

.for(@icons); .-each(@value) {
    @name:  extract(@value, 1);
    .zmdi-@{name} {
        &:before {
            content: extract(@value, 2);
        }
    }
}
```
