### ISSUE TITLE
Use nested pseudo classes for LESS

### ISSUE THREAD

**Issue by gustavohenke** [zavoloklom/material-design-iconic-font#11]
Hey,
It would be great to change the icon declarations for LESS to use nested pseudo classes, instead of
simply using them directly.
The problem is, I can't reuse them because of the pseudo class.

For example:
```less
.my-icon:before:extend( .@{md-css-prefix}-check:before ) {}
```

This one won't work. However, if icons were defined this way:

```less
.@{md-css-prefix}-check {
  &:before {
    content: "\e123";
  }
}
```

...and I reused that class without pseudo classes, everything would work.
What do you think, @zavoloklom? I'm able to send you an PR if you're fine.
