### ISSUE TITLE
Add scss variables

### ISSUE THREAD

**Issue by matmkian** [zavoloklom/material-design-iconic-font#14]
Hi,

First I'd like to thank you for your great work !

It would be great if you can provide scss/less variables for each icon.
We could use it with pseudo element.

```scss
$md-var-arrow-drop-up: '\f296';

.up-button:after {
    content: $md-var-arrow-drop-up;
}
```
