### ISSUE TITLE
OTS Parsing Error

### ISSUE THREAD

**Issue by tanmaydesai89** [zavoloklom/material-design-iconic-font#75]
I am receiving following error:

`Failed to decode downloaded font: http://*.com/fonts/Material-Design-Iconic-Font.woff?v=2.1.0
dashboard:1 OTS parsing error: invalid version tag`

Please advise.

**Comment by zavoloklom** [comment]
@tanmaydesai89,
Current version is 2.2.0, maybe you should try that number.

**Comment by tanmaydesai89** [comment]
@zavoloklom I tried that an hour back. No luck. 

`@font-face {
       font-family: Material-Design-Iconic-Font;
       src: url(../fonts/Material-Design-Iconic-Font.woff2?v=2.2.0) format('woff2'), url(../fonts/Material-Design-Iconic-Font.woff?v=2.2.0) format('woff'), url(../fonts/Material-Design-Iconic-Font.ttf?v=2.2.0) format('truetype')
}`

This is vendor.css that grunt is generating.

**Comment by zavoloklom** [comment]
@tanmaydesai89,
Try to remove version `../fonts/Material-Design-Iconic-Font.woff2`.
P.S. I don't know what you are doing. If you can describe your situation in more detail, than I can try to give more useful advice.

**Comment by thandaanda** [comment]
So, it turns out that when this fonts are loaded on the browser, content-type is changed to "text/html", any reason why?

**Comment by thandaanda** [comment]
Finally found the solution, you need to move fonts to public/fonts directory, you can do it by writing following code in `copy/dist` task of Grunt.

``` css
{
                        expand: true,
                        cwd: '<%= yeoman.client %>/bower_components/material-design-iconic-font/dist/fonts',
                        src: ['*.*'],
                        dest: '<%= yeoman.dist %>/public/fonts'
                }
```
